[package]
name = "stack_max"
version = "0.1.0"
authors = ["t-eckert <t_eckert@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
